version: '3.8'

services:
  postgres:
    image: postgres:16.6-alpine
    container_name: pos-postgres
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
      POSTGRES_DB: pos_db
      TZ: America/La_Paz
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
